// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
void rotate_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_pastel_purple_png);    // assets\pastel_purple.png
LV_IMG_DECLARE(ui_img_ring_png);    // assets\ring.png
LV_IMG_DECLARE(ui_img_watch_hour_modern_png);    // assets\watch_hour_modern.png
LV_IMG_DECLARE(ui_img_watch_min_modern_png);    // assets\watch_min_modern.png
LV_IMG_DECLARE(ui_img_watch_sec_modern_png);    // assets\watch_sec_modern.png
LV_IMG_DECLARE(ui_img_1117480529);    // assets\icons8-walk-48.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
